### ISSUE TITLE
New user SSO - user save failed "email" has already been taken - PostgreSQL

### ISSUE THREAD

**Issue by tonyclemmey** [flipboxfactory/saml-sp#123]
Hello

When using PostgreSQL, on the first SSO login attempt it is successful and a Craft user account is created and attributes are mapped correctly such as email, firstName, and lastName etc.

If the new SSO user logs out, and then tries to log in again login is broken

```
Exception – yii\base\UserException

User save failed: {"email":["Email \"name@example.com\" has already been taken."]}

in /home/vendor/flipboxfactory/saml-sp/src/services/login/User.php

$this->trigger(
            static::EVENT_BEFORE_USER_SAVE,
            $event
        );
 
        if (! \Craft::$app->getElements()->saveElement($user)) {
            Saml::error(
                'User save failed: ' . \json_encode($user->getErrors())
            );
            throw new UserException("User save failed: " . \json_encode($user->getErrors()));
        }
 
        return true;
    }
 
```

```
PHP version :8.0.5
Database driver & version:   PostgreSQL 13.3
Craft edition & version: Craft Pro 3.7.4
SAML Service Provider version: 2.6.9
```

**Comment by dsmrt** [comment]
:wave: @tonyclemmey 

I'm wondering if this happening: https://github.com/flipboxfactory/saml-sp/issues/91#issuecomment-738323697

Do you have the config `useEmailAsUsername` set in `config/general.php`?

**Comment by tonyclemmey** [comment]
Hey @dsmrt 

Yes, I do have the `useEmailAsUsername` set to `true` in `config/general.php` 

and inside `saml-sp.php`

```
return [
     'defaultGroupAssignments' => [
         3,
     ],
];
```

Using the same Azure AD account & same users etc (testing purposes) this seems to only happen for the PostgresSQL version and when using the MySQL version it seems to be fine.

**Comment by dsmrt** [comment]
Hello @tonyclemmey, 

I was able to replicate this. This isn't a Postgres thing. The NameID (SAML's unique id for the user) in it's current format is giving you issues because it's probably not an email address. I bet the user id/NameID is coming through as a uuid from AzureAD.

The plugin uses NameID as the user id so you need that (NameID) to either do one of the 2 following options:
1. Come through as the email, since you are using the `useEmailAsUsername` config.
2. Overwrite the NameID on the Craft side, in the plugin at "Username/NameID Override" in the IdP Edit page on the Configuration tab for Azure AD

See the screenshots below on where to edit these:


*Option 1, within Azure AD*
--
![Screen Shot 2021-07-27 at 5 12 15 PM](https://user-images.githubusercontent.com/1995478/127240109-175e383a-9d1c-451c-a5b6-9aa3813bc935.png)

*Option 2, within the SAML SP plugin in Craft*
--
![Screen Shot 2021-07-27 at 5 22 28 PM](https://user-images.githubusercontent.com/1995478/127240125-13489f20-fdac-4d7a-b392-e6446276f045.png)


Side note:
Here is a good way to debug what is coming through (to check the SAML Response etc):
```tail -f storage/logs/web.log | grep -A 10 '\[saml-'```

You can also use a debug tracer like this: https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace

**Comment by tonyclemmey** [comment]
Hey @dsmrt,

Thank you for your response. It is very helpful indeed. I think I just overlooked the Username/NameID field value for a server/site I did not actually have access to and only glanced at it via a screen share. I must have mistakenly just seen the placeholder text as a field override value instead, which was not the case.

Maybe It's a trivial thing but sometimes the placeholder can already be the same as the default value, which is then clear on what you need to override.

**Comment by dsmrt** [comment]
@tonyclemmey, 

Good point on the default placeholder. Might be better to reference the email value in the description as a common value to overwrite and leave the placeholder blank. That does seem like a UX/UI issue. 

I'm going to close but let me know if anything else comes up.
