### ISSUE TITLE
Craft Internal Server Error after SSO response; general questions

### ISSUE THREAD

**Issue by camelskyscraper** [flipboxfactory/saml-sp#135]
First, I may be about to ask some "dumb" questions. And I don't generally use GitHub so I'm probably doing this wrong. Please excuse my ignorance and be as gentle as you can.

Second, I am completely new to SSO and trying to muddle through getting this working in conjunction with a corporate IT department. They know a lot about SSO, but nothing about Craft.

Third, unfortunately I am not able to get SSO credentials to test this myself. I have to rely on somebody at IT trying it for me while I watch via a Zoom screen share.

It appears that we have the plugin set up with a Service Provider and an Identity Provider. If it matters, the IdP is Azure AD. When the tester clicked the SSO login button it appeared that the request went out to the Identity Provider and came back to Craft. The resulting screen showed a default Internal Server Error from Craft and the URL in the address bar is the ACS URL for the Service Provider marked "(My Provider)" in the plugin. I don't know what is supposed to happen at that point or what might be going wrong. I need help to know what to do next.

Questions:
- does the SSO user need to have an account in the Craft site for SSO to work?
- how can a Craft User be associated with an SSO user? (for example, how would Craft know if this SSO user should have Admin access, what User Groups they might be in, etcetera)
- how do I access whatever data might come back from the successful SSO signin?
- is it possible to set up a Service Provider in one environment for use in another environment? e.g. set up locally in dev and then push it to staging without have to recreate the Service Provider. It seems like the plugin automatically reads the site URL and there isn't a way to change that. Maybe there is something I am missing there.

It is critical to the project that we get SSO to work, so your support is greatly appreciated. We have already licensed the plugin.

If you have instructions for gathering troubleshooting information I can relay them to my contacts at the IT department.

And, to make things even more fun, I am will be out of the office for two weeks starting at end of day today. So if you could give me anything helpful today — pointers, follow up questions, whatever — that will be extra appreciated. Thank you.

**Comment by dsmrt** [comment]
:wave: @camelskyscraper ,

No such thing as dumb questions with sso and SAML. It can be a confusing beast! 

Since you using Azure AD, take a look at my video walkthrough. It's pretty helpful even if you aren't use Azure AD.
https://saml-sp.flipboxfactory.com/idps/azure-ad.html#azure-ad

As far as the error goes, check the logs for things matching string like `[error]` and `[saml-`. Here is an example tail command you can run: `tail -f storage/logs/web.log | grep -A 10 '\[saml-'`.

I wouldn't be surprised if the error has something to do with the email missing (mapping is wrong) or there is a signature verification failure.

> does the SSO user need to have an account in the Craft site for SSO to work?
The plugin will create the user on successful login. There's an config to turn this off if needed (let me know if you want this turned off).

> how can a Craft User be associated with an SSO user? (for example, how would Craft know if this SSO user should have Admin access, what User Groups they might be in, etcetera)
The plugin and SAML generally uses the NameID from the Response (from the IdP) as the username in the SP (Craft). That is the default but you can overwrite this if needed and use something like an email if needed (check the configure tab).

You can map user groups with a config: https://saml-sp.flipboxfactory.com/configure/settings.html#group-configuration-group-assignment . This allows the IdP send over the group names as strings that should match the Craft user group handles.
If you need more complexity, look at the event example here: https://saml-sp.flipboxfactory.com/configure/events.html#assign-user-to-a-user-group-based-on-a-property.
Also note the user groups must be created in Craft ahead of time. This allows you to add permissions as needed and to manage those in the project config.

> how do I access whatever data might come back from the successful SSO signin?
Map the user data from the IdP to user fields in Craft. (watch the video walkthrough like mentioned above).

> is it possible to set up a Service Provider in one environment for use in another environment? e.g. set up locally in dev and then push it to staging without have to recreate the Service Provider. It seems like the plugin automatically reads the site URL and there isn't a way to change that. Maybe there is something I am missing there.
Unfortunately, the plugin doesn't support that. You may be able to change the site url by using an environmental variable for those site urls and create multiple environments on the same one quickly. Just know you have to coordinate the sharing of metadata with the IdP for each environment. 

I'll look into this myself too, it's been something that's bugged me in the past. Just know I may not be able to get to it right away.

**Comment by dsmrt** [comment]
FYI I added this: https://github.com/flipboxfactory/saml-sp/issues/136

**Comment by camelskyscraper** [comment]
I am both grateful for your speedy detailed response and shameful that I missed the video previously. SUPER helpful, thanks!

One additional and important question for now: if I set up the `loginPath` to be the SSO URL does that mean it is not possible to log in normally as a Craft user anymore? Ideally we'd skip the Craft login screen entirely for most users, but some of us won't have SSO credentials. Maybe there is a tricky way to have the "standard" `loginPath` be the SSO and have some secret login URL for those in the know.

**Comment by dsmrt** [comment]
With the login path, you don't have to use it as I suggest if that doesn't work for you. Part of why I recommend adding the sso request path to the `loginPath` is to utilize Craft's built-in `requireLogin` functionality. So when you hit a page that requires login, you'll be redirected to the IdP for login, then redirected back to the page you were attempting to go to.

With that said, you can set the `loginPath` to a page of your liking with the usual login form. Then take the sso login request path the plugin provides and put that in a link along with the form. For example:

```html
<a href="/sso/login/request/<uid>?RelayState={{ craft.app.user.returnUrl }}">Login with SSO (Azure AD)</a>
``` 

Note I added the RelayState (a SAML thing) so the user will be redirected back to where they were intending to go. I *think* that twig code is correct!

**Comment by camelskyscraper** [comment]
Great, thanks. I think you've provided lots of great information for me to follow up on when I'm back in two weeks. Feel free to close the "issue" and I'll add a new one if needed. <high five>

**Comment by dsmrt** [comment]
Sounds good. Will close this for now. Let me know how it goes when you are diving back in. 😃

**Comment by camelskyscraper** [comment]
Great, thank you. We have been able to make a successful login, so I think this "issue" is officially closed (again). I really appreciate you holding my hand on this. Next will be group implementation, for which I will refer to your notes and the docs. Thanks again!
