### ISSUE TITLE
RelayState Variable Scenario - Does not redirect back to the given URL

### ISSUE THREAD

**Issue by jeffsikes** [flipboxfactory/saml-sp#16]
This may be a "working as intended" item, but there is a scenario where the RelayState variable does not return you to the expected page.

**Scenario:**
- You are **already** logged in.
- You click a link like "<a href="{{ loginUrl }}?RelayState=/news-feed">Visit our News Feed</a>".
- SAML-SP seems to be saying "um...you're already logged in..." and just redirecting back to the homepage without a trip to the IdP. The RelayState isn't being stored or at least it's not being utilized in this scenario.

**Comment by dsmrt** [comment]
After a bit of investigation, I found this really difficult to fix from my side and am going to suggest you handle it on yours.

**Why this happens?**
Craft takes over before I can do much about this due to us using the the `loginPath` general configuration. Since we are using that Craft sees that you are already login and doesn't want to take you back there, to the login page. 

**How to handle this**
Correct me if I'm wrong but I was thinking you could do something like this:
```twig
{% if currentUser %}
     <a href="{{ destination }}">Destination</a>
{% else %}
     <a href="{{ myLoginPath }}?RelayState={{ destination }}">Destination</a>
{% endif %}
```
