### ISSUE TITLE
Breaking Changes in v2.0 (Events)

### ISSUE THREAD

**Issue by benjaminkohl** [flipboxfactory/saml-sp#35]
I am in the process of updating the plugin from v1.0.8 to v2.0.4 and the updating guide says there are breaking changes when using the Craft/Yii2 events and that the code will need to be refactored but it doesn't describe what has changed and I am not immediately seeing it.

We are using the UserLogin event and from what I can tell, the classes involved haven't changed and neither has the event parameter (at least in terms of how to get the user). What is it that I am not seeing that I need to change as part of this update?

**Comment by dsmrt** [comment]
The breaking changes are, we have switched from using the [LightSaml](https://github.com/lightSAML/lightSAML) lib to [simplesamlphp](https://github.com/simplesamlphp/saml2). So any references to `LightSaml` should be removed/refactored. For instance, the Response object that is passed in the `EVENT_AFTER_RESPONSE_TO_USER` (thru the `\flipbox\saml\sp\events\UserLogin` event) is now `SAML2\Response` instead of `\LightSaml\Model\Protocol\Response`. So working with the object is going to work differently. For examples, take a look at this code here: `\flipbox\saml\sp\services\login\User::transform` [or here](https://github.com/flipboxfactory/saml-sp/blob/2.0.4/src/services/login/User.php#L175).

Generally, all references to LightSaml need to be updated but if you don't have that problem, all should work as usual. I really want to make sure people are diligent about updating. Backup up the db (there are some migrations that run) and test login before pushing to production. If you need any help that you don't feel comfortable sharing here, ping me thru our [contact us](https://www.flipboxdigital.com/contact) and we can share some code. I want to make sure this is smooth for you!

**Comment by dsmrt** [comment]
Here's another thing that has changed that could have some impact: 
https://github.com/flipboxfactory/saml-sp/compare/1.0.8...master?diff=split#diff-9e7982c22dcbe44ffed844c176aa0b39L135

**Comment by dsmrt** [comment]
Also, if you use `responseAttributeMap` from within the `config/saml-sp.php`, the parameters have changed. If you can move away from that config and use the GUI in the CP, that'd be ideal. That way it's per IdP and not global.

**Comment by benjaminkohl** [comment]
Ah, thanks for the information. We weren't doing anything with that Response object in our module's event handler so I guess our code is unaffected by the change. I was thinking that maybe something about registering the event handler specifically had changed.

The site in question hasn't launched yet which is why we wanted to get the update out of the way now and I backed up the DB so we should be pretty safe. Thanks for the help!

**Comment by dsmrt** [comment]
Great! Let me know how all of that goes, or if you have any feedback.

**Comment by benjaminkohl** [comment]
It looks like everything went smoothly because the Okta login process still works. Thank you.
